In [1]:
import pandas as pd
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
wine = load_wine()
X = wine.data
y = wine.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [6]:
gaussian_model = GaussianNB()
gaussian_model.fit(X_train, y_train)

y_pred_gaussian = gaussian_model.predict(X_test)

print("Gaussian Naive Bayes Performance:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_gaussian):.4f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_gaussian))
print("Classification Report:")
print(classification_report(y_test, y_pred_gaussian))

Gaussian Naive Bayes Performance:
Accuracy: 1.0000
Confusion Matrix:
[[19  0  0]
 [ 0 21  0]
 [ 0  0 14]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00        14

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54



In [7]:
multinomial_model = MultinomialNB()
multinomial_model.fit(X_train, y_train)

y_pred_multinomial = multinomial_model.predict(X_test)

print("\nMultinomial Naive Bayes Performance:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_multinomial):.4f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_multinomial))
print("Classification Report:")
print(classification_report(y_test, y_pred_multinomial))


Multinomial Naive Bayes Performance:
Accuracy: 0.8889
Confusion Matrix:
[[19  0  0]
 [ 0 18  3]
 [ 2  1 11]]
Classification Report:
              precision    recall  f1-score   support

           0       0.90      1.00      0.95        19
           1       0.95      0.86      0.90        21
           2       0.79      0.79      0.79        14

    accuracy                           0.89        54
   macro avg       0.88      0.88      0.88        54
weighted avg       0.89      0.89      0.89        54



In [9]:
print("\nModel Comparison:")
if accuracy_score(y_test, y_pred_gaussian) > accuracy_score(y_test, y_pred_multinomial):
    print("Gaussian Naive Bayes performs better.")
    best_model = gaussian_model
else:
    print("Multinomial Naive Bayes performs better.")
    best_model = multinomial_model

print("\nPredictions on a few test samples using the better model:")
for i in range(5):
    sample_index = i
    actual_label = y_test[sample_index]
    predicted_label = best_model.predict(X_test[sample_index].reshape(1, -1))[0]
    print(f"Sample {sample_index+1}: Actual Label = {actual_label}, Predicted Label = {predicted_label}")


Model Comparison:
Gaussian Naive Bayes performs better.

Predictions on a few test samples using the better model:
Sample 1: Actual Label = 0, Predicted Label = 0
Sample 2: Actual Label = 0, Predicted Label = 0
Sample 3: Actual Label = 2, Predicted Label = 2
Sample 4: Actual Label = 0, Predicted Label = 0
Sample 5: Actual Label = 1, Predicted Label = 1
